app/routes.php
<?php

Route::get('/', array('as' => 'website.index', 'uses' => 'WebsiteController@index'));


Route::group(array('before' => 'auth'), function () {
	Route::get('session/logout', array('as' => 'logout', 'uses' => 'SessionController@logout'));
	Route::get('session/panel', array('as' => 'session.user_panel', 'uses' => 'SessionController@user_panel'));
});

Route::get('signin', array('as' => 'session.signin', 'uses' => 'SessionController@signin'));
Route::post('signin', array('as' => 'session.signin_store','uses' => 'SessionController@signin_store'));

Route::get('usuarios/recovery-password/{id}', array('as' => 'recovery_password_id','uses' => 'SessionController@recoverypassword'));
Route::post('password', array('as' => 'password', 'uses' => 'SessionController@password'));
Route::post('recovery', array('as' => 'session.recovery_password', 'uses' => 'SessionController@recovery_password'));

Route::get('registro', array('as' => 'session.signup', 'uses' => 'SessionController@signup'));
Route::post('signup', array('as' => 'session.signup_store', 'uses' => 'SessionController@signup_store'));

Route::group(array('prefix' => 'panel/player', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.player.index', 'uses' => 'PlayersPanelController@index'));
	Route::resource('tutors', 'PlayerTutorsController');
	Route::get('tournaments', ['as' => 'panel.player.tournaments.index', 'uses' => 'PlayerTournamentController@index']);
	Route::get('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe', 'uses' => 'PlayerTournamentController@subscribe']);
	Route::post('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe_store', 'uses' => 'PlayerTournamentController@subscribe_store']);
	Route::delete('tournaments/user_tournaments/{id}', ['as' => 'panel.admin.user_tournaments.destroy', 'uses' => 'PlayerTournamentController@subscribe_destroy']);
	// Route::resource('tournaments', 'PlayerTournamentController');
	Route::get('history', ['as' => 'panel.player.history.index', 'uses' => 'PlayerHistoryController@index']);
	Route::resource('fields', 'PlayerFieldController');

	Route::get('user_stage/{stage_id}/{tournament_id}', ['as' => 'panel.player.user_stage.store', 'uses' => 'PlayerUserStageController@store']);
	Route::get('history/{user_stage_id}', ['as' => 'panel.player.user_stage.stage', 'uses' => 'PlayerUserStageController@stage']);

});

Route::group(array('prefix' => 'panel/admin', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.admin.index', 'uses' => 'AdminPanelController@index'));
	Route::resource('players', 'AdminPlayerController');
	Route::resource('fields', 'AdminFieldController');
	Route::resource('tournaments', 'AdminTournamentController');

	Route::get('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.index', 'uses' => 'AdminStageController@index']);
	Route::get('tournaments/{tournament_id}/stages/create', ['as' => 'panel.admin.stages.create', 'uses' => 'AdminStageController@create']);
	Route::post('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.store', 'uses' => 'AdminStageController@store']);
	Route::get('tournaments/{tournament_id}/stages/{id}/edit', ['as' => 'panel.admin.stages.edit', 'uses' => 'AdminStageController@edit']);
	Route::put('tournaments/stages/{id}', ['as' => 'panel.admin.stages.update', 'uses' => 'AdminStageController@update']);
	Route::delete('tournaments/stages/{id}', ['as' => 'panel.admin.stages.destroy', 'uses' => 'AdminStageController@destroy']);

	Route::get('history/{tournament_id}', ['as' => 'panel.admin.history.index', 'uses' => 'AdminHistoryController@index']);
	Route::get('history/user_stage/create/{stage_id}/{tournament_id}/{user_id}', ['as' => 'panel.admin.user_stage.create', 'uses' => 'AdminUserStageController@create']);
	Route::post('history/user_stage', ['as' => 'panel.admin.user_stage.store', 'uses' => 'AdminUserStageController@store']);
});

app/models/Player.php
<?php

class Player extends \Eloquent
{
	protected $fillable = ['phone_number', 'birthday', 'birthplace', 'allergies', 'other_sports', 'category_id'];

	public function category ()
	{
		return $this->belongsTo('Category');
	}
}

app/models/Tutor.php
<?php

class Tutor extends \Eloquent {
	
	protected $fillable = ['first_name', 'last_name', 'email', 'phone_number'];

	protected $table = 'tutors';

	function full_name () {

		return $this->first_name . ' ' . $this->last_name;
	}

	public static $rules_validate = array(
		'first_name' 	=> 'required',
		'last_name' 	=> 'required'
	);

	public static $rules_messages = array(
	    'first_name.required' => 'El nombre es requerido',
	    'last_name.required' => 'Apellidos son requeridos'
	);
}

app/controllers/PlayersController.php
<?php

class PlayersController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /players
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /players/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /players
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}

	/**
	 * Display the specified resource.
	 * GET /players/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /players/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /players/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /players/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/controllers/TutorsController.php
<?php

class TutorsController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /tutors
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /tutors/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /tutors
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}

	/**
	 * Display the specified resource.
	 * GET /tutors/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /tutors/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /tutors/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /tutors/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/panel/player/tutors/_form.blade.php
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('first_name', 'Nombre(s)', array('class' => 'input-required')) }}
			{{ Form::text('first_name', null,array('class' => 'form-control required')) }}
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('last_name', 'Apellidos', array('class' => 'input-required')) }}
			{{ Form::text('last_name', null,array('class' => 'form-control required')) }}
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('phone_number', 'Teléfono', array('class' => 'input-required')) }}
			{{ Form::text('phone_number', null, array('class' => 'masked form-control required', 'placeholder' => '(664) 123-4567')) }}
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('email', 'Correo electrónico de tutor', array('class' => 'input-required')) }}
			{{ Form::text('email', null, array('class' => 'form-control required')) }}
		</div>
	</div>
</div>

app/views/panel/player/tutors/create.blade.php
@extends('layout.player')
@section('content')

{{ Form::model($tutor, array('route' => array('panel.player.tutors.store', $tutor->id), 'autocomplete' => 'off', 'id' => 'form-tutor', 'method' => 'POST')) }}

<div class="row">
	<div class="col-md-6">
		<h3 class="m0 title">Nuevo tutor</h3>
	</div>
	<div class="col-md-6" align="right">
		{{  Form::submit('Guardar', array('class' => 'btn btn-success mr10')) }}
		<a href="{{ redirect_back() }}">Regresar</a>
	</div>
</div>
<hr />
@include('panel.player.tutors._form')

{{ Form::close() }}

<script type="text/javascript" src="{{ url('assets/javascripts/panel/player/tutors.js') }}"></script>

@stop

app/views/panel/player/tutors/edit.blade.php
@extends('layout.player')
@section('content')

{{ Form::model($tutor, array('route' => array('panel.player.tutors.update', $tutor->id), 'autocomplete' => 'off', 'id' => 'form-tutor', 'method' => 'PUT')) }}

<div class="row">
	<div class="col-md-6">
		<h3 class="m0 title">Editar tutor</h3>
	</div>
	<div class="col-md-6" align="right">
		{{  Form::submit('Guardar cambios', array('class' => 'btn btn-success mr10')) }}
		<a href="{{ redirect_back() }}">Regresar</a>
	</div>
</div>
<hr />
@include('panel.player.tutors._form')

{{ Form::close() }}

<script type="text/javascript" src="{{ url('assets/javascripts/panel/player/tutors.js') }}"></script>

@stop

app/views/panel/player/tutors/index.blade.php
@extends('layout.player')
@section('content')
	
	<div class="row">
		<div class="col-md-6">
			<h3 class="m0 title">Mis tutores</h3>
		</div>
		<div class="col-md-6" align="right"> 
			<a href="{{ route('panel.player.tutors.create') }}" class="btn btn-default-success"> <i class="ion-plus-round"></i> Agregar nuevo tutor</a>
		</div>
	</div>
	<hr />

	<div>
		<table class="table table-bordered">
			<thead>
				<th>
					Nombre
				</th>
				<th>
					Teléfono
				</th>
				<th width="200px">
				</th>
			</thead>
			<tbody>
				@foreach($tutors as $key => $tutor)
				<tr>
					<td>
						{{ $tutor->full_name() }}
					</td>
					<td>
						{{ $tutor->phone_number }}
					</td>
					<td align="center">
						<div class="btn-group" role="group">
						  	{{ Form::open(array('method' => 'DELETE', 'route' => array('panel.player.tutors.destroy', $tutor->id))) }}
						  		<a type="button" href="{{ route('panel.player.tutors.edit', $tutor->id) }}" class="btn btn-default"> <i class="ion-gear-a"></i> Editar</a>
						  		<a type="button" class="destroy-record btn btn-default"> <i class="ion-trash-a"></i> Eliminar</a>
						  	{{ Form::close() }}
						</div>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
@stop