app/routes.php
<?php

Route::get('/', array('as' => 'website.index', 'uses' => 'WebsiteController@index'));


Route::group(array('before' => 'auth'), function () {
	Route::get('session/logout', array('as' => 'logout', 'uses' => 'SessionController@logout'));
	Route::get('session/panel', array('as' => 'session.user_panel', 'uses' => 'SessionController@user_panel'));
});

Route::get('signin', array('as' => 'session.signin', 'uses' => 'SessionController@signin'));
Route::post('signin', array('as' => 'session.signin_store','uses' => 'SessionController@signin_store'));

Route::get('usuarios/recovery-password/{id}', array('as' => 'recovery_password_id','uses' => 'SessionController@recoverypassword'));
Route::post('password', array('as' => 'password', 'uses' => 'SessionController@password'));
Route::post('recovery', array('as' => 'session.recovery_password', 'uses' => 'SessionController@recovery_password'));

Route::get('registro', array('as' => 'session.signup', 'uses' => 'SessionController@signup'));
Route::post('signup', array('as' => 'session.signup_store', 'uses' => 'SessionController@signup_store'));

Route::group(array('prefix' => 'panel/player', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.player.index', 'uses' => 'PlayersPanelController@index'));
	Route::resource('tutors', 'PlayerTutorsController');
	Route::get('tournaments', ['as' => 'panel.player.tournaments.index', 'uses' => 'PlayerTournamentController@index']);
	Route::get('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe', 'uses' => 'PlayerTournamentController@subscribe']);
	Route::post('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe_store', 'uses' => 'PlayerTournamentController@subscribe_store']);
	Route::delete('tournaments/user_tournaments/{id}', ['as' => 'panel.admin.user_tournaments.destroy', 'uses' => 'PlayerTournamentController@subscribe_destroy']);
	// Route::resource('tournaments', 'PlayerTournamentController');
	Route::get('history', ['as' => 'panel.player.history.index', 'uses' => 'PlayerHistoryController@index']);
	Route::resource('fields', 'PlayerFieldController');

	Route::get('user_stage/{stage_id}/{tournament_id}', ['as' => 'panel.player.user_stage.store', 'uses' => 'PlayerUserStageController@store']);
	Route::get('history/{user_stage_id}', ['as' => 'panel.player.user_stage.stage', 'uses' => 'PlayerUserStageController@stage']);

});

Route::group(array('prefix' => 'panel/admin', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.admin.index', 'uses' => 'AdminPanelController@index'));
	Route::resource('players', 'AdminPlayerController');
	Route::resource('fields', 'AdminFieldController');
	Route::resource('tournaments', 'AdminTournamentController');

	Route::get('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.index', 'uses' => 'AdminStageController@index']);
	Route::get('tournaments/{tournament_id}/stages/create', ['as' => 'panel.admin.stages.create', 'uses' => 'AdminStageController@create']);
	Route::post('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.store', 'uses' => 'AdminStageController@store']);
	Route::get('tournaments/{tournament_id}/stages/{id}/edit', ['as' => 'panel.admin.stages.edit', 'uses' => 'AdminStageController@edit']);
	Route::put('tournaments/stages/{id}', ['as' => 'panel.admin.stages.update', 'uses' => 'AdminStageController@update']);
	Route::delete('tournaments/stages/{id}', ['as' => 'panel.admin.stages.destroy', 'uses' => 'AdminStageController@destroy']);

	Route::get('history/{tournament_id}', ['as' => 'panel.admin.history.index', 'uses' => 'AdminHistoryController@index']);
	Route::get('history/user_stage/create/{stage_id}/{tournament_id}/{user_id}', ['as' => 'panel.admin.user_stage.create', 'uses' => 'AdminUserStageController@create']);
	Route::post('history/user_stage', ['as' => 'panel.admin.user_stage.store', 'uses' => 'AdminUserStageController@store']);
});

app/models/Tournament.php
<?php

class Tournament extends \Eloquent {
	
	protected $fillable = ['name', 'start_date', 'finish_date', 'description', 'status', 'gender_id'];

    /**
     * Status => 0 : Active, 1 : Finished, 2 : Cancel
     */

	protected $table = 'tournaments';

	public static $rules_validate = array(
		'name' 	=> 'required'
	);

	public static $rules_messages = array(
	    'name.required' => 'El nombre es requerido'
	);

    /**
     * Check if the player is signed in the tournament
     * @return boolean
     */
    public function is_subscribed () {
        
        $user = Auth::user();
            
        $subscribed = UserTournament::where('user_id', $user->id)->where('tournament_id', $this->id)->first();

        if ($subscribed) return true;

        return false;
    }

    public function stage () {

        return $this->hasMany('Stage');
    }

    public function gender () {
        
        return $this->belongsTo('Gender');
    }
}

app/views/panel/admin/tournaments/_form.blade.php
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('name', 'Nombre', array('class' => 'input-required')) }}
			{{ Form::text('name', null, array('class' => 'form-control required')) }}
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('gender_id', 'Genero', array('class' => 'input-required' )) }}
			{{ Form::select('gender_id', $genders, null, array('class' => 'form-control')) }}
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('start_date', 'Fecha de inicio', array('class' => 'input-required')) }}
			{{ Form::text('start_date', null, array('class' => 'form-control required datetime-date')) }}
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('finish_date', 'Fecha de finalización', array('class' => 'input-required', 'placeholder' => 'Tijuana Baja California')) }}
			{{ Form::text('finish_date', null, array('class' => 'form-control required datetime-date')) }}
		</div>
	</div>
</div>
<div class="form-group">
	@if($tournament->id)
		{{ Form::label('status', 'Estatus', array('class' => '')) }}
		<div class="radio-inline">
		  <label>
		    <input type="radio" name="status" value="0" @if($tournament->status == 0) {{ 'checked' }} @endif }}>
		    Activo
		  </label>
		</div>
		<div class="radio-inline">
		  <label>
		    <input type="radio" name="status" value="1" @if($tournament->status == 1) {{ 'checked' }} @endif }}>
		    Finalizado
		  </label>
		</div>
		<div class="radio-inline">
		  <label>
		    <input type="radio" name="status" value="2" @if($tournament->status == 2) {{ 'checked' }} @endif }}>
		    Cancelado
		  </label>
		</div>
	@endif
</div>

<div class="form-group">
	{{ Form::label('description', 'Descripción', array('class' => '')) }}
	{{ Form::textarea('description', null, array('class' => 'form-control')) }}
</div>

app/views/panel/admin/tournaments/create.blade.php
@extends('layout.admin')
@section('content')

{{ Form::model($tournament, array('route' => array('panel.admin.tournaments.store', $tournament->id), 'autocomplete' => 'off', 'id' => 'form-tournament', 'method' => 'POST')) }}

<div class="row">
	<div class="col-md-6">
		<h3 class="m0 title">Nuevo torneo</h3>
	</div>
	<div class="col-md-6" align="right">
		{{  Form::submit('Guardar', array('class' => 'btn btn-success mr10')) }}
		<a href="{{ redirect_back() }}">Regresar</a>
	</div>
</div>
<hr />
<ol class="breadcrumb">
    <li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
    <li><a href="{{ route('panel.admin.tournaments.index') }}">Torneos</a></li>
    <li class="active">Nuevo registro</li>
</ol>
@include('panel.admin.tournaments._form')

{{ Form::close() }}

<script type="text/javascript" src="{{ url('assets/javascripts/panel/admin/tournaments.js') }}"></script>

@stop

app/views/panel/admin/tournaments/edit.blade.php
@extends('layout.admin')
@section('content')

{{ Form::model($tournament, array('route' => array('panel.admin.tournaments.update', $tournament->id), 'autocomplete' => 'off', 'id' => 'form-tournament', 'method' => 'PUT')) }}

<div class="row">
	<div class="col-md-6">
		<h3 class="m0 title">Editar torneo</h3>
	</div>
	<div class="col-md-6" align="right">
        <a href="{{ route('panel.admin.stages.index', $tournament->id) }}" class="btn btn-primary mr10"> <i class="ion-ios-browsers-outline"></i> Administrar etapas</a>
		{{  Form::submit('Guardar cambios', array('class' => 'btn btn-success mr10')) }}
		<a href="{{ redirect_back() }}">Regresar</a>
	</div>
</div>
<hr />
<ol class="breadcrumb">
    <li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
    <li><a href="{{ route('panel.admin.tournaments.index') }}">Torneos</a></li>
    <li class="active">Editar registro</li>
</ol>
@include('panel.admin.tournaments._form')

{{ Form::close() }}

<script type="text/javascript" src="{{ url('assets/javascripts/panel/admin/tournaments.js') }}"></script>

@stop

app/views/panel/admin/tournaments/index.blade.php
@extends('layout.admin')
@section('content')
	
	<div class="row">
		<div class="col-md-6">
			<h3 class="m0 title">Torneos</h3>
		</div>
		<div class="col-md-6" align="right"> 
			<a href="{{ route('panel.admin.tournaments.create') }}" class="btn btn-default-success">
				<i class="ion-plus-round"></i> Agregar nuevo torneo
			</a>
		</div>
	</div>
	<hr/>
	<ol class="breadcrumb">
      	<li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
      	<li class="active">Torneos</li>
    </ol>
	<table class="table table-bordered">
		<thead>
			<th>
				Nombre
			</th>
			<th width="480px">
			</th>
		</thead>
		<tbody>
			@foreach($tournaments as $tournament)
				<tr>
					<td>
						{{ $tournament->name }}
					</td>
					<td align="center">
						<div class="btn-group" role="group">
						  	{{ Form::open(array('method' => 'DELETE', 'route' => array('panel.admin.tournaments.destroy', $tournament->id))) }}
						  		<a href="{{ route('panel.admin.tournaments.show', $tournament->id) }}" class="btn btn-default"> <i class=""></i> Ver detalles</a>
						  		<a href="{{ route('panel.admin.history.index', $tournament->id) }}" class="btn btn-default"> <i class=""></i> Historial</a>
						  		<a href="{{ route('panel.admin.stages.index', $tournament->id) }}" class="btn btn-default"><i class="ion-ios-browsers-outline"></i>  Etapas {{ $tournament->stage->count() }} </a>
						  		<a href="{{ route('panel.admin.tournaments.edit', $tournament->id) }}" class="btn btn-default"> <i class="ion-gear-a"></i> Editar</a>
						  		<a class="destroy-record btn btn-default"> <i class="ion-trash-a"></i> Eliminar</a>
						  	{{ Form::close() }}
						</div>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
	@if($tournaments->count() == 0)
		<i>Aún sin registros</i>
	@endif
	{{ $tournaments->links() }}

@stop

app/views/panel/admin/tournaments/show.blade.php
@extends('layout.admin')
@section('content')

<div class="row">
    <div class="col-md-6">
        <h3 class="m0 title">Torneo: <b class="color-black">{{ $tournament->name }}</b></h3>
    </div>
    <div class="col-md-6" align="right">
        <a href="{{ route('panel.admin.tournaments.edit', $tournament->id) }}" class="btn btn-default mr10"> <i class="ion-gear-a"></i> Editar</a>
        <a href="{{ redirect_back() }}">Regresar</a>
    </div>
</div>
<hr />
<ol class="breadcrumb">
    <li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
    <li><a href="{{ route('panel.admin.tournaments.index') }}">Torneos</a></li>
    <li class="active">Detalles de registro</li>
</ol>

<div>
    <h3 class="title">Detalles del torneo</h3>
    <hr />
    <div class="well">
        <div>
            <div class="form-group row">
                <label class="col-sm-1 control-label">Nombre:</label>
                <div class="col-sm-3 form-group">
                    {{ $tournament->name }}
                </div>
                <label class="col-sm-1 control-label">Inicia:</label>
                <div class="col-sm-3">
                    {{ format_date($tournament->start_date) }}
                </div>
                <label class="col-sm-1 control-label">Finaliza:</label>
                <div class="col-sm-3">
                    {{ format_date($tournament->finish_date) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div>
                <label class="col-sm-2 control-label">Descripción:</label>
                <div class="col-sm-4">
                    {{ ($tournament->description) ? $tournament->description : '---' }}
                </div>
            </div>
            <div>
                <label class="col-sm-2 control-label">Genero:</label>
                <div class="col-sm-4">
                    {{ ($tournament->gender) ? $tournament->gender->name : '---' }}
                </div>
            </div>
        </div>
    </div>
    <h3 class="title">Jugadores registrados</h3>
    <table class="table table-bordered">
        <thead>
            <th width="50px">
                #
            </th>
            <th>
                Nombre
            </th>
            <th width="250px"></th>
        </thead>
        <tbody>
            @foreach($users as $key => $data)
            <tr>
                @if($data->user)
                    <td align="center">
                        {{ $key + 1 }}
                    </td>
                    <td>
                        {{ $data->user->full_name }}
                    </td>
                    <td align="center">
                        <div class="btn-group" role="group">
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('panel.admin.user_tournaments.destroy', $data->id))) }}
                            <a type="button" href="{{ route('panel.admin.players.edit', $data->user->id) }}" class="btn btn-default"> <i class="ion-gear-a"></i> Ver detalles</a>
                            <a class="destroy-record btn btn-default"> <i class="ion-trash-a"></i> Eliminar</a>
                        {{ Form::close() }}
                        </div>
                    </td>
                @else
                    <i>No disponible</i>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>
    @if($users->count() == 0)
        <i>Aún sin registros</i>
    @endif
</div>
@stop