app/routes.php
<?php

Route::get('/', array('as' => 'website.index', 'uses' => 'WebsiteController@index'));


Route::group(array('before' => 'auth'), function () {
	Route::get('session/logout', array('as' => 'logout', 'uses' => 'SessionController@logout'));
	Route::get('session/panel', array('as' => 'session.user_panel', 'uses' => 'SessionController@user_panel'));
});

Route::get('signin', array('as' => 'session.signin', 'uses' => 'SessionController@signin'));
Route::post('signin', array('as' => 'session.signin_store','uses' => 'SessionController@signin_store'));

Route::get('usuarios/recovery-password/{id}', array('as' => 'recovery_password_id','uses' => 'SessionController@recoverypassword'));
Route::post('password', array('as' => 'password', 'uses' => 'SessionController@password'));
Route::post('recovery', array('as' => 'session.recovery_password', 'uses' => 'SessionController@recovery_password'));

Route::get('registro', array('as' => 'session.signup', 'uses' => 'SessionController@signup'));
Route::post('signup', array('as' => 'session.signup_store', 'uses' => 'SessionController@signup_store'));

Route::group(array('prefix' => 'panel/player', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.player.index', 'uses' => 'PlayersPanelController@index'));
	Route::resource('tutors', 'PlayerTutorsController');
	Route::get('tournaments', ['as' => 'panel.player.tournaments.index', 'uses' => 'PlayerTournamentController@index']);
	Route::get('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe', 'uses' => 'PlayerTournamentController@subscribe']);
	Route::post('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe_store', 'uses' => 'PlayerTournamentController@subscribe_store']);
	Route::delete('tournaments/user_tournaments/{id}', ['as' => 'panel.admin.user_tournaments.destroy', 'uses' => 'PlayerTournamentController@subscribe_destroy']);
	// Route::resource('tournaments', 'PlayerTournamentController');
	Route::get('history', ['as' => 'panel.player.history.index', 'uses' => 'PlayerHistoryController@index']);
	Route::resource('fields', 'PlayerFieldController');

	Route::get('user_stage/{stage_id}/{tournament_id}', ['as' => 'panel.player.user_stage.store', 'uses' => 'PlayerUserStageController@store']);
	Route::get('history/{user_stage_id}', ['as' => 'panel.player.user_stage.stage', 'uses' => 'PlayerUserStageController@stage']);

});

Route::group(array('prefix' => 'panel/admin', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.admin.index', 'uses' => 'AdminPanelController@index'));
	Route::resource('players', 'AdminPlayerController');
	Route::resource('fields', 'AdminFieldController');
	Route::resource('tournaments', 'AdminTournamentController');

	Route::get('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.index', 'uses' => 'AdminStageController@index']);
	Route::get('tournaments/{tournament_id}/stages/create', ['as' => 'panel.admin.stages.create', 'uses' => 'AdminStageController@create']);
	Route::post('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.store', 'uses' => 'AdminStageController@store']);
	Route::get('tournaments/{tournament_id}/stages/{id}/edit', ['as' => 'panel.admin.stages.edit', 'uses' => 'AdminStageController@edit']);
	Route::put('tournaments/stages/{id}', ['as' => 'panel.admin.stages.update', 'uses' => 'AdminStageController@update']);
	Route::delete('tournaments/stages/{id}', ['as' => 'panel.admin.stages.destroy', 'uses' => 'AdminStageController@destroy']);

	Route::get('history/{tournament_id}', ['as' => 'panel.admin.history.index', 'uses' => 'AdminHistoryController@index']);
	Route::get('history/user_stage/create/{stage_id}/{tournament_id}/{user_id}', ['as' => 'panel.admin.user_stage.create', 'uses' => 'AdminUserStageController@create']);
	Route::post('history/user_stage', ['as' => 'panel.admin.user_stage.store', 'uses' => 'AdminUserStageController@store']);
});

app/views/layout/admin.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Panel de Administrador</title>
	<link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	
	{{  stylesheet_link_tag('panel/application.css') }}

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{{ url('assets/stylesheets/panel/sidebar.css') }}" />
	<link rel="stylesheet" type="text/css" href="{{ url('assets/stylesheets/panel/style.css') }}" />
	
	{{ javascript_include_tag('panel/application.js') }}

</head>
<body>
	<!-- <div class="message-notification" id="message-notification"> Mensaje </div> -->
	<nav class="navbar navbar-default navbar-fixed-top">
      	<div class="container">
        	<div class="navbar-header">
          		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
          		</button>
          		<a class="navbar-brand" href="">
					<img src="{{ url('assets/images/golfnoroeste-logo-png.png') }}" width="120px" class="img-responsive" />
				</a>
        	</div>

        	<div class="collapse navbar-collapse" id="">
	          	<ul class="nav navbar-nav navbar-right">
	          		<li>
	          			<a href="{{ route('logout') }}" class="ion-log-out"> Cerrar sesión</a>
	          		</li>
	          	</ul>
	        </div>
      	</div>
    </nav>
    <div class="container-fluid">
      	<div class="row">
	        <div class="col-sm-2 col-md-2 col-md-offset-1 sidebar">
	          	<ul class="nav nav-sidebar">
		            <li class="{{ nav_option_active(array('/', '')) }}">
		            	<a href="{{ route('panel.admin.index') }}"> <i class="icon ion-home"></i> Inicio <span class="sr-only">(current)</span></a>
		            </li>
		            <li class="{{ nav_option_active(array('players')) }}">
		            	<a href="{{ route('panel.admin.players.index') }}">
		            		<i class="icon ion-person-stalker"></i> Jugadores
		            	</a>
		            </li>
		            <li class="{{ nav_option_active(array('fields')) }}">
		            	<a href="{{ route('panel.admin.fields.index') }}"> <i class="icon ion-leaf"></i> Campos</a>
		            </li>
		            <li class="{{ nav_option_active(array('tournaments')) }}">
		            	<a href="{{ route('panel.admin.tournaments.index') }}"> <i class="icon ion-bonfire"></i> Torneos</a>
		            </li>
	          	</ul>
	          	<!-- 
	          	<ul class="nav nav-sidebar">
		            <li><a href="#"> <i class="icon ion-gear-a"></i> Configuración</a></li>
	          	</ul>
	          	<ul class="nav nav-sidebar">
		            <li><a href="">Nav item again</a></li>
		            <li><a href="">One more nav</a></li>
		            <li><a href="">Another nav item</a></li>
	          	</ul>-->
	        </div>
	        <div class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-3 main">
	        	@if (Session::has('message'))
				    <div class="alert {{ Session::get('alert-class') }}">
				    	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				    	{{ Session::get('message') }}
				    </div>
				@endif
				
	        	@yield('content')
	        </div>
      	</div>
    </div>
	
	<!-- <footer class="footer">
      	<div class="copyright">
	      	<div class="container">
	      		<div class="row">
	      			<div class="col-md-12">
	      				Copyright 2015 Golf | Todos los derechos reservados
	      			</div>
	      		</div>
	      	</div>
      	</div>
    </footer> -->

    <script type="text/javascript" src="{{ url('assets/javascripts/panel/helpers.js') }}"></script>
</body>
</html>

app/views/layout/player.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Panel de jugador</title>
	<link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	{{  stylesheet_link_tag('panel/application.css') }}
	<link rel="stylesheet" type="text/css" href="{{ url('assets/stylesheets/panel/sidebar.css') }}" />
	<link rel="stylesheet" type="text/css" href="{{ url('assets/stylesheets/panel/style.css') }}" />
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
	{{ javascript_include_tag('panel/application.js') }}
</head>
<body>
	<!-- <div class="message-notification" id="message-notification"> Mensaje </div> -->
	<nav class="navbar navbar-default navbar-fixed-top">
      	<div class="container">
        	<div class="navbar-header">
          		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
          		</button>
          		<a class="navbar-brand" href="">
					<img src="{{ url() }}/assets/images/golfnoroeste-logo-png.png" width="120px" class="img-responsive" />
				</a>
        	</div>
        	<ul class="nav navbar-nav">
	          		<li>
	          			<a href="{{ route('website.index') }}" class="ion-earth"> Ir a Sitio Web</a>
	          		</li>
	          	</ul>
        	<div class="collapse navbar-collapse" id="">
	          	<ul class="nav navbar-nav navbar-right">
	          		<li>
	          			<a>¡<b>Hola</b> {{ Auth::user()->full_name }}!</a>
	          		</li>
	          		<li>
	          			<a href="{{ route('logout') }}" class="ion-log-out"> Cerrar sesión</a>
	          		</li>
	          	</ul>
	        </div>
      	</div>
    </nav>
    <div class="container-fluid">
      	<div class="row">
	        <div class="col-sm-2 col-md-2 col-md-offset-1 sidebar">
	          	<ul class="nav nav-sidebar">
		            <li class="{{ nav_option_active(array('/', '')) }}">
		            	<a href="{{ route('panel.player.index') }}"> <i class="icon ion-home"></i> Inicio <span class="sr-only">(current)</span></a>
		            </li>
		            <li class="{{ nav_option_active(array('tournaments')) }}">
		            	<a href="{{ route('panel.player.tournaments.index') }}"> <i class="icon ion-bonfire"></i> Torneos</a>
		            </li>
		             <li class="{{ nav_option_active(array('history')) }}">
		            	<a href="{{ route('panel.player.history.index') }}"> <i class="icon ion-ios-bookmarks-outline"></i> Historial de juegos</a>
		            </li>
		            <li class="{{ nav_option_active(array('fields')) }}">
		            	<a href="{{ route('panel.player.fields.index') }}"> <i class="icon ion-leaf"></i> Campos</a>
		            </li>
		            <li class="{{ nav_option_active(array('tutors')) }}">
		            	<a href="{{ route('panel.player.tutors.index') }}"> <i class="icon ion-ios-people"></i> Mis Tutores </a>
		            </li>
	          	</ul>
	          	<!-- <ul class="nav nav-sidebar">
		            <li><a href="#"> <i class="icon ion-gear-a"></i> Configuración</a></li>
	          	</ul>
	          	<ul class="nav nav-sidebar">
		            <li><a href="">Nav item again</a></li>
		            <li><a href="">One more nav</a></li>
		            <li><a href="">Another nav item</a></li>
	          	</ul>-->
	        </div>
	        <div class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-3 main">
	        	@if (Session::has('message'))
				    <div class="alert {{ Session::get('alert-class') }}">
				    	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				    	{{ Session::get('message') }}
				    </div>
				@endif
	        	@yield('content')
	        </div>
      	</div>
    </div>
	
	<!-- <footer class="footer">
      	<div class="copyright">
	      	<div class="container">
	      		<div class="row">
	      			<div class="col-md-12">
	      				Copyright 2015 Golf | Todos los derechos reservados
	      			</div>
	      		</div>
	      	</div>
      	</div>
    </footer> -->
    <script type="text/javascript" src="{{ url('assets/javascripts/panel/helpers.js') }}"></script>
</body>
</html>

app/views/layout/website.blade.php
<!DOCTYPE html>
<html lang="es-MX">
	<head>
		<title>Golf</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="keywords" content="" /> 
		{{  stylesheet_link_tag('website/application.css') }}
		<link rel="stylesheet" type="text/css" href="{{ url('assets/stylesheets/website/style.css') }}">
		<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
		<link rel="icon" type="image/png" href="" sizes="32x32">
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
		{{ javascript_include_tag('website/application.js') }}

		<style>
			.hero-signin { background: url("{{ url('assets/images/golf3.jpg') }}") no-repeat; }
			.hero-signup { background: url("{{ url('assets/images/golf2.jpg')  }}") no-repeat; }
		</style>
	</head>

	<body data-spy="scroll" data-target=".main-nav">
		<header class="st-navbar">
			<nav class="navbar navbar-default navbar-website navbar-fixed-top clearfix bg-tranparent">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sept-main-nav">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="">
							<img src="assets/images/golfnoroeste-logo-png.png" width="120px" class="img-responsive" />
						</a>
					</div>
					<div class="collapse navbar-website navbar-collapse main-nav" id="sept-main-nav">
						<ul class="nav navbar-nav navbar-right">
							<li class=""><a class="" href="{{ route('website.index') }}"> Inicio </a></li>
							@if(Auth::check())
								<li>
									<a href="{{ route('session.user_panel') }}"> 
										Perfil <i class="fa fa-cog fa-sm"></i>
									</a>
								</li>
							@else
								<li><a href="{{ route('session.signup') }}" class="">Registrarse</a></li>
								<li><a href="{{ route('session.signin') }}" class="">Iniciar sesion</a></li>
							@endif
						</ul>
					</div>
				</div>
			</nav>
		</header>
		
		@yield('content')

		<!-- <footer class="footer">
	      	<div class="copyright">
		      	<div class="container">
		      		<div class="row">
		      			<div class="col-md-12">
		      				Copyright 2015 Golf | Todos los derechos reservados
		      			</div>
		      		</div>
		      	</div>
	      	</div>
	    </footer> -->

		<script type="text/javascript" src="{{ url('assets/javascripts/website/helpers.js') }}"></script>
	</body>
</html>