app/routes.php
<?php

Route::get('/', array('as' => 'website.index', 'uses' => 'WebsiteController@index'));


Route::group(array('before' => 'auth'), function () {
	Route::get('session/logout', array('as' => 'logout', 'uses' => 'SessionController@logout'));
	Route::get('session/panel', array('as' => 'session.user_panel', 'uses' => 'SessionController@user_panel'));
});

Route::get('signin', array('as' => 'session.signin', 'uses' => 'SessionController@signin'));
Route::post('signin', array('as' => 'session.signin_store','uses' => 'SessionController@signin_store'));

Route::get('usuarios/recovery-password/{id}', array('as' => 'recovery_password_id','uses' => 'SessionController@recoverypassword'));
Route::post('password', array('as' => 'password', 'uses' => 'SessionController@password'));
Route::post('recovery', array('as' => 'session.recovery_password', 'uses' => 'SessionController@recovery_password'));

Route::get('registro', array('as' => 'session.signup', 'uses' => 'SessionController@signup'));
Route::post('signup', array('as' => 'session.signup_store', 'uses' => 'SessionController@signup_store'));

Route::group(array('prefix' => 'panel/player', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.player.index', 'uses' => 'PlayersPanelController@index'));
	Route::resource('tutors', 'PlayerTutorsController');
	Route::get('tournaments', ['as' => 'panel.player.tournaments.index', 'uses' => 'PlayerTournamentController@index']);
	Route::get('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe', 'uses' => 'PlayerTournamentController@subscribe']);
	Route::post('tournaments/{tournament_id}/subscribe', ['as' => 'panel.player.tournaments.subscribe_store', 'uses' => 'PlayerTournamentController@subscribe_store']);
	Route::delete('tournaments/user_tournaments/{id}', ['as' => 'panel.admin.user_tournaments.destroy', 'uses' => 'PlayerTournamentController@subscribe_destroy']);
	// Route::resource('tournaments', 'PlayerTournamentController');
	Route::get('history', ['as' => 'panel.player.history.index', 'uses' => 'PlayerHistoryController@index']);
	Route::resource('fields', 'PlayerFieldController');

	Route::get('user_stage/{stage_id}/{tournament_id}', ['as' => 'panel.player.user_stage.store', 'uses' => 'PlayerUserStageController@store']);
	Route::get('history/{user_stage_id}', ['as' => 'panel.player.user_stage.stage', 'uses' => 'PlayerUserStageController@stage']);

});

Route::group(array('prefix' => 'panel/admin', 'before' => 'auth'), function () {
	Route::get('/', array('as' => 'panel.admin.index', 'uses' => 'AdminPanelController@index'));
	Route::resource('players', 'AdminPlayerController');
	Route::resource('fields', 'AdminFieldController');
	Route::resource('tournaments', 'AdminTournamentController');

	Route::get('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.index', 'uses' => 'AdminStageController@index']);
	Route::get('tournaments/{tournament_id}/stages/create', ['as' => 'panel.admin.stages.create', 'uses' => 'AdminStageController@create']);
	Route::post('tournaments/{tournament_id}/stages/', ['as' => 'panel.admin.stages.store', 'uses' => 'AdminStageController@store']);
	Route::get('tournaments/{tournament_id}/stages/{id}/edit', ['as' => 'panel.admin.stages.edit', 'uses' => 'AdminStageController@edit']);
	Route::put('tournaments/stages/{id}', ['as' => 'panel.admin.stages.update', 'uses' => 'AdminStageController@update']);
	Route::delete('tournaments/stages/{id}', ['as' => 'panel.admin.stages.destroy', 'uses' => 'AdminStageController@destroy']);

	Route::get('history/{tournament_id}', ['as' => 'panel.admin.history.index', 'uses' => 'AdminHistoryController@index']);
	Route::get('history/user_stage/create/{stage_id}/{tournament_id}/{user_id}', ['as' => 'panel.admin.user_stage.create', 'uses' => 'AdminUserStageController@create']);
	Route::post('history/user_stage', ['as' => 'panel.admin.user_stage.store', 'uses' => 'AdminUserStageController@store']);
});

app/models/Field.php
<?php

class Field extends \Eloquent {
	
	protected $fillable = ['name', 'description', 'place'];

	protected $table = 'fields';

	public static $rules_validate = array(
		'name' 	=> 'required',
		'place'     => 'required'
	);

	public static $rules_messages = array(
	    'name.required' => 'El nombre es requerido',
	    'place.required' => 'El campo lugar es requerido'
	);
}

app/views/panel/admin/fields/_form.blade.php
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('name', 'Nombre', array('class' => 'input-required')) }}
			{{ Form::text('name', null, array('class' => 'form-control required ')) }}
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			{{ Form::label('place', 'Lugar', array('class' => 'input-required')) }}
			{{ Form::text('place', null, array('class' => 'form-control required', 'placeholder' => 'Tijuana Baja California')) }}
		</div>
	</div>
</div>
<div class="form-group">
	{{ Form::label('description', 'Descripción', array('class' => '')) }}
	{{ Form::textarea('description', null, array('class' => 'form-control')) }}
</div>

app/views/panel/admin/fields/create.blade.php
@extends('layout.admin')
@section('content')

{{ Form::model($field, array('route' => array('panel.admin.fields.store', $field->id), 'autocomplete' => 'off', 'id' => 'form-field', 'method' => 'POST')) }}

<div class="row">
	<div class="col-md-6">
		<h3 class="m0 title">Nuevo campo</h3>
	</div>
	<div class="col-md-6" align="right">
		{{  Form::submit('Guardar', array('class' => 'btn btn-success mr10')) }}
		<a href="{{ redirect_back() }}">Regresar</a>
	</div>
</div>
<hr />
<ol class="breadcrumb">
    <li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
    <li><a href="{{ route('panel.admin.fields.index') }}">Campos</a></li>
    <li class="active">Nuevo registro</li>
</ol>
@include('panel.admin.fields._form')

{{ Form::close() }}

<script type="text/javascript" src="{{ url('assets/javascripts/panel/admin/fields.js') }}"></script>

@stop

app/views/panel/admin/fields/edit.blade.php
@extends('layout.admin')
@section('content')

{{ Form::model($field, array('route' => array('panel.admin.fields.update', $field->id), 'autocomplete' => 'off', 'id' => 'form-field', 'method' => 'PUT')) }}

<div class="row">
	<div class="col-md-6">
		<h3 class="m0 title">Editar campo</h3>
	</div>
	<div class="col-md-6" align="right">
		{{  Form::submit('Guardar cambios', array('class' => 'btn btn-success mr10')) }}
		<a href="{{ redirect_back() }}">Regresar</a>
	</div>
</div>
<hr />
<ol class="breadcrumb">
    <li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
    <li><a href="{{ route('panel.admin.fields.index') }}">Campos</a></li>
    <li class="active">Editar registro</li>
</ol>

@include('panel.admin.fields._form')

{{ Form::close() }}

<script type="text/javascript" src="{{ url('assets/javascripts/panel/admin/fields.js') }}"></script>

@stop

app/views/panel/admin/fields/index.blade.php
@extends('layout.admin')
@section('content')
	
	<div class="row">
		<div class="col-md-6">
			<h3 class="m0 title">Campos</h3>
		</div>
		<div class="col-md-6" align="right"> 
			<a href="{{ route('panel.admin.fields.create') }}" class="btn btn-default-success">
				<i class="ion-plus-round"></i> Agregar nuevo campo
			</a>
		</div>
	</div>
	<hr/>
	<ol class="breadcrumb">
	    <li><a href="{{ route('panel.admin.index') }}">Inicio</a></li>
	    <li>Campos</li>
	</ol>
	<table class="table table-bordered">
		<thead>
			<th>
				Nombre
			</th>
			<th>
				Lugar
			</th>
			<th width="200px">
			</th>
		</thead>
		<tbody>
			@foreach($fields as $field)
				<tr>
					<td>
						{{ $field->name }}
					</td>
					<td>
						{{ $field->place }}
					</td>
					<td align="center">
						<div class="btn-group" role="group">
						  	{{ Form::open(array('method' => 'DELETE', 'route' => array('panel.admin.fields.destroy', $field->id))) }}
						  		<a type="button" href="{{ route('panel.admin.fields.edit', $field->id) }}" class="btn btn-default"> <i class="ion-gear-a"></i> Editar</a>
						  		<a type="button" class="destroy-record btn btn-default"> <i class="ion-trash-a"></i> Eliminar</a>
						  	{{ Form::close() }}
						</div>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
	@if($fields->count() == 0)
		<i>Aún sin registros</i>
	@endif
	{{ $fields->links() }}

@stop